name: Create release

on:
  push:
    tags:
      - v*

jobs:
  release-linux-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Read VERSION file
      id: getversion
      run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

    - name: Build
      run:  go build -ldflags="-X main.version=${{ steps.getversion.outputs.version }}"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          LICENSE.txt
          kazinga


